services:
  - type: web
    name: integrove-testn8nai
    env: docker
    region: frankfurt # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: main # optional (defaults to master) 
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 1
    healthCheckPath: /
    disk:
      name: n8naiDisk
      mountPath: /home/node/.n8n
      sizeGB: 10

databases:
  - name: n8nDB
    plan: starter
